### ISSUE TITLE
Instructions to enable sslv2 support on modern distros

### ISSUE THREAD

**Issue by DaniloNC** [OWASP/O-Saft#41]
I'm trying to use o-saft on a Ubuntu 15.04 VM but I cannot make it work with SSLv2.0

I have already enabled sslv2.0 support on openssl following/adapting instructions here http://blog.opensecurityresearch.com/2013/05/fixing-sslv2-support-in-kali-linux.html and I have also tried to enable sslv2.0 on Net::SSLeay following http://www.techstacks.com/howto/enable-sslv2-methods-in-netssleay.html

When I try to execute the o-saft tool this warning shows up:

```
danilonc@tcc:~/tcc$ perl o-saft.pl +info encrypted.google.com                                                                                                                                                        
=== reading: ./.o-saft.pl (No such file or directory) ===
**WARNING: SSL version 'SSLv2' not supported by openssl; ignored
```

How can i make it work?

**Comment by EnDe** [comment]
can you please check your Net/SSLeay.pm and search for
   sub new_x_ctx
if it contains (right at the beginning) something like:
  warn "ssl_version has been set to 2, but this version of OpenSSL has been compiled without SSLv2 support";

then you SSLeay was not compiled with enabled SSLv2 support..

To see which SSLeay.pm is in use, see
  o-saft.pl +version --v
To check if the underlaying openssl supports SSLv2, try something liek:
  openssl s_client -ssl2 -connect localhost:443
if you get openssl's usage, SSLv2 is not supported.

Final hint: ifyou just want to check for ciphers, try with +cipherraw instead of +cipher .

**Comment by EnDe** [comment]
The documentation contains an INSTALLATION section now. It's available with
   o-saft.pl +help=INSTALL
See https://www.owasp.org/index.php/O-Saft/Documentation#INSTALLATION

In short:
  compile and install openssl, then patch SSLeay.xs as described and compile and install the module.

**Comment by EnDe** [comment]
There exist a full description now how to enable SSLv2 (and others) in various versions of openssl and in Net::SSLeay. Please see
  o-saft.pl --help=INSTALLATION     # version from gihub. january 2016
or
  https://www.owasp.org/index.php/O-Saft/Documentation#INSTALLATION
