### ISSUE TITLE
enhancement: o-saft.pl command line option to fail when vulnerability is found.

### ISSUE THREAD

**Issue by bbaassssiiee** [OWASP/O-Saft#52]
I request a non-zero exit code when one of the tests fails, or at least an option for that. As a consumer I can then clone, run, and **fail** when a test fails, without programming.

With the current output **I have to parse myself**:

```
Connection is safe against BEAST attack (any cipher):no ( <<N/A as --no-SSLv2 in use>> TLSv11)
Connection is safe against BREACH attack:no (<<NOT YET IMPLEMENTED>>)
Connection is safe against CRIME attack:yes
Connection is safe against DROWN attack:no (<<N/A as --no-SSLv2 in use>>)
Connection is safe against FREAK attack:yes
Connection is safe against Heartbleed attack:yes
Connection is safe against Logjam attack:yes
Connection is safe against Lucky 13 attack:no
Connection is safe against POODLE attack:yes
Connection is safe against RC4 attack:yes
Connection is safe against Sweet32 attack:no
Target does not support SSLv2:no (<<N/A as --no-SSLv2 in use>>)
Target does not support SSLv3:yes
Target supports PFS (selected cipher):yes
Target TLS Session Ticket is random:yes
```

When I would launch with the proposed --fail flag the exit code is non-zero when any tests says no.

`./o-saft.pl --fail --no-warning --no-header +vulns mysite.org --legacy=compact
`

**Comment by bbaassssiiee** [comment]
This will enable continuous integration of near zero-day vulnerabilities.

**Comment by EnDe** [comment]
short answer: implemented with the option --exitcode , see [o-saft.pl 1f57b787c5c9150876fb9ea152a8f9f82ed1f3eb](https://github.com/OWASP/O-Saft/commit/1f57b787c5c9150876fb9ea152a8f9f82ed1f3eb)

See https://www.owasp.org/index.php/O-Saft/Documentation#--exitcode

long answer: please see following comments

**Comment by EnDe** [comment]
long answer: 

As said before, the functionality is implemented, 'cause I see the practical use-case. However, it's experimental for now (means option and functionality may change slightly in near furure), please check when new versions are used.

Clone from github, and everything should work as requested.

Background:
one of O-Saft's concepts is to "show important information" and to inform about the performed checks based on these informations. The check results are basically "yes" or "no". It leaves the interpretation, if the result is "good" or "bad", to the user.  This means that all reported results are unbiased.
Said this, it's obvious that o-saft.pl cannot return any other status beside the printed results (which *are* the status).
The idea is, that postprocessors should be used to use the results for scoring or alike. This is another concept, and o-saft.pl is prepared for the ease use of prostprocessors.

As it is common sense that a status code other then 0 indicates that something is wrong, such a status code would violate this concept as it is biased.
A status code other than 0 would also make using o-saft.pl in a pipe much more difficult.

Now, I see the practical use in a pipe or process chain, which simplifies the handling of the results, sometimes. 
So, the requirement makes sense, but throws a couple of questions to be answered. The requirement, as descibed in this issue, is to return a status code other than 0, if any check reports "no". Could be done (is done 11oct2016:), but is not the complete truth. What about the other checks, like the sizes, the DNS checks? What about the ciphers, are medium ciphers subject for fail? What about incomplete checks because the server did not return proper data (i.e. DH parameters). What about failed checks, which could be considered unimportant in the tested environment (i.e. some STS or compliance checks)?

These are the same questions as for scoring the results (like other tools do). It's a matter of personal opinion and/or the attributes of the tested enviroinment, if "something" should be considered "good" or "bad".
However, if a user is aware of such problems, she can configure O-Saft to do only the relevant checks. Other tools cannot do this, and hence score everything, wether important, usefull, practical, ... or not.
Please see next comment for a practical example.

How to deal with these questions?
I.g. the "--fail" functionality needs to be configurable by the user.
Best example why this is necessary, is the +cipher command. Is any supported cipher other than HIGH subject for fail? Should MEDIUM ciphers not fail? Or ask your marketing people what they think about disabling DES-CBC3-SHA (which is weak now), just to pass the test?

My opinion is, that a configurable "--fail" in conjunction with the existing configuration of the checks to be performed, can do the trick.

Conclusion: there is no -and will not be- a general "--fail" option. Instead, we provide some options if various kinds of checks should be subject for an exit code. 
With this concepts, it's up to the user to configure O-Saft to return a proper exit code. This should not be difficult for experianced users with special requirements ;-)
For now, --exitcode just counting the "no" checks, is the starting points.

Here we go, this desciption is subject for discussion. Please provide you opinions.

**Comment by bbaassssiiee** [comment]
curl has a -f, --fail option that does the same when you request URLs, if there's an http response code signaling an error, then curl --fail wil fail (even silently) with an non-zero exit code.

**Comment by EnDe** [comment]
Here is a practical example why a general "--fail" would not return the expected results.

Using   `o-saft.pl mysite.org --exitcode +vulns`  would return results like shown in the very first comment above.
Looking at these results, we see 6 "no" checks: BEAST, BREACH, DROWN, Lucky13, Sweet32 and SSLv2. My opinion is -please correct me if wrong- that only 2 checks should count for the exit code: Lucky13 and Sweet32.

Currently, havng the concepts (see previous comment) in mind, the solution to filter the improper checks would be to use prostprocessors:

   `o-saft.pl mysite.org --exitcode +vulns|grep -v '(<<'|egrep -q 'no( |$)' || echo fail`


o-saft.pl could be configured to do the proper tests only. There are at least 3 ways to do it:

1. using proper commands only:

    `o-saft.pl mysite.org --exitcode +crime +freak +heartbleed +logjam +lucky13 +poodle +rc4 +sloth +sweet32 +time +hassslv3 +pfs_cipher +session_random`

2. using .o-saft.pl (the traditional way):

cat > .o-saft.pl <<EoT
--host=mysite.org
--exitcode
+crime
+freak
+heartbleed
+logjam
+lucky13
+poodle
+rc4
+sloth
+sweet32
+time
+hassslv3
+pfs_cipher
+session_random
EoT

   `o-saft.pl`

3. using .o-saft.pl (advanced usage):

cat > .o-saft.pl <<EoT
--host=mysite.org
--exitcode
+heureca
 # define new command +heureca , all following (bevor EoT)must be in one line
--cfg_cmd=heureca=crime freak heartbleed logjam lucky13 poodle rc4 sloth sweet32 time hassslv3 pfs_cipher session_random
EoT

   `o-saft.pl`


Note that creating .o-saft.pl mustbe done once in the directory where o-saft.pl
will be started.

----
Hope this helps to understand how O-Saft handles various situation and how to configure it for very spezial purposes.

**Comment by EnDe** [comment]
> compare curl, that has a ...

curl does one thing, one request, one action which could fail. Hence the --fail corresponds to this one action. Easy.
We have dozent of actions, where each could fail. Not so easy :-(
Anyway, even if we implement someting like  --exit-on-first-fail  the question remains: what exactly the condition for "fail" is. This is what I tried to descibe in my "long answer" above.

**Comment by EnDe** [comment]
Thinking about the --exit-on-first-fail option, it's still implemented using just atomic commands:

   `o-saft.pl mysite.org --exitcode +crime` 
   `o-saft.pl mysite.org --exitcode +freak`
   `o-saft.pl mysite.org --exitcode +rc4`
   `…`

You get it?

**Comment by bbaassssiiee** [comment]
I just liked the idea to poll github for the newest vulnerability tests on a daily basis using my continuous integration server, to run the test suite against my sites and to raise an exception when any test fails. Jenkins will mail me an then I can investigate. **With your proposal I have to maintain a post-processor, but where?** In --exit-on-first-fail it is not relevant which test fails, **failing fast is OK**. I just want to know **that** my site is in trouble with regards to https. And I cannot configure the new test of tomorrow. Doing config work goes against the idea of 

> zero-day mitigation

.
On the other hand creating a report like xunit does is another approach, a nice summary page with failing tests, and succeeding tests. More work, and in essence the test-run should still fail because more than zero tests failed.

**Comment by EnDe** [comment]
Hmm, slightly disagree with "have to maintain a post-processor".
As I descibed before, --exitcode shoud do what you want for now.
Just if you think that some tests should not be counted for fail, you need to do somthing, beside postprocessors, I gave 3 examples.

Note, did you clone github to get --exitcode working? just pulling o-saft.pl is not sufficient.

**Comment by bbaassssiiee** [comment]
I will run the CI to try this when back in office tomorrow.

**Comment by EnDe** [comment]
--exitcode now also counts weak ciphers and protocols (only TLSv12 and HIGH ciphers are not weak).
More options for fine tuning will be implemented soon.

**Comment by EnDe** [comment]
Implemented with some fine tuning in https://github.com/OWASP/O-Saft/commit/1ddcabae9601b35008eff53c923985e128e692bd
