### ISSUE TITLE
A few questions about wildcard certificate

### ISSUE THREAD

**Issue by fredomgc** [OWASP/O-Saft#64]
I have a few questions about wildcard certificate (I am not sure, if I encountered bug or expected behaviour).

When I run
`./o-saft.pl +check google.com`

it outputs following:

...
`Connected hostname matches certificate's subject:	no (google.com <> *.google.com)`
^^ Is this bug or expected behaviour? Hostname actually matches certificate's subject, because of wildcard certificate.

...
`Certificate's wildcard does not match hostname:	yes`
^^ Is this bug? Hostname matches certificate's subject, so answer should be "no".
^^ Also, according to the documentation, "The idea is to report yes if the result is considered "secure"". But is it secure result, when hostname does NOT match certificate?

**Comment by EnDe** [comment]
This is expected and documented behaviour, please see
  https://www.owasp.org/index.php/O-Saft/Documentation#.2Bcheck
or off-site
  o-saft.pl --help=RESULTS

Brief explanation
 certificates with wildcard CN, Subject and/or SubjectAltName are bad or even insecure practice for secure application, however it's common practice to use them for example in CDNs
We are aware about this, hence these two checks and their probably misleading result(s) are documented.

Technically  some.tld does never match *.some.tld, wether as regex nor in sence of a certificate wildcard. That's why "Connected hostname matches ..." is no. The same applies to "Certificate's wildcard does not match ...".
Things are a little bit different for  whatever.some.tld and *.some.tld.

Please look at following example (valid 17. Febr. 2017):
