### ISSUE TITLE
Incorrect result for self-signed test

### ISSUE THREAD

**Issue by fredomgc** [OWASP/O-Saft#65]
I noticed some bug regarding to the test for self-signed certificate.

I was testing two sites:
- amazon.com - without self-signed certificate (issued by Symantec)
- is.ssos.cz - with self-signed certificate (issued by untrusted 'SSOS Certification Authority', SSOS is abbreviation for some high-school)

but always with the same result:

```
./o-saft.pl +selfsigned https://www.amazon.com/
...
Certificate is not self-signed:     	no (CONNECTED(00000003)
```

```
./o-saft.pl +selfsigned https://is.ssos.cz/
...
Certificate is not self-signed:     	no (num=20:unable to get local issuer certificate)
```

I was using Ubuntu Linux and O-Saft 16.12.16. To exclude some misconfiguration on my local machine, I performed same test on different PC, with relatively fresh install of Windows 7. Here I get incorrect result, but in the oposite way:

```
perl o-saft.pl +selfsigned https://www.amazon.com/
...
Certificate is not self-signed:         yes
```

```
perl o-saft.pl +selfsigned https://is.ssos.cz/
...
Certificate is not self-signed:         yes

```

On my Ubuntu Linux, here is output of:
- echo|openssl s_client -connect www.amazon.com:443 -- http://pastebin.com/raw/y7RT6Knr
- echo|openssl s_client -connect is.ssos.cz:443 -- http://pastebin.com/raw/RW4bS3fy

I am ready to post some additional info, but I am not sure, which will be usefull.

**Comment by EnDe** [comment]
this is what I get:
```
o-saft.pl +selfsigned  --nodns --tracekey https://www.amazon.com/
#[selfsigned]:      Certificate Validity (signature):   	0 (ok)
#[selfsigned]:      Certificate is not self-signed:     	yes
```
which looks ok and is what should be expected. Right?

According your description, you get different results on different machines. This is a known behaviour and it's documented, please see "Target Certificate Chain Verification" in [O-Saft Documentation](https://www.owasp.org/index.php/O-Saft/Documentation#Checks_.28general.29)
or 
``o-saft.pl --help=LIMITATIONS``

Ubuntu is known to come with its own openssl installation, it's sometimes hard to get it working as expected, i.e. due to the location of the CAs which should be in /etc/ssl/certs but might be somewhere else. Please use o-saft's --v option and check if the CAs are located in the path reported by ca_path in --v output.

It's strange that your Windows machine reports "not self-signed: yes". Do you have the root CA installed there?

With  ``openssl version -d`` you can see where openssl looks for the CAs. This is what you also see in o-saft's --v output.

You can fiddle around with some other options of o-saft to get closer to the behaviour, please the at "Target Certificate Chain Verification"  (link above).
